name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - New operation
        - New trigger event
        - Existing operation improvement
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: What problem would this solve? How would you use it?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches you've tried?
